FROM node:20.19.3-alpine

WORKDIR /usr/src/app

# Instala dependências do sistema para Prisma
RUN apk add --no-cache openssl

# Copia arquivos de configuração
COPY package*.json ./
COPY prisma ./prisma/

# Instala dependências
RUN npm ci

# Copia o restante do código
COPY . .

EXPOSE 3000 9229

USER node

CMD ["npm", "run", "start:dev"]